language: node_js

node_js:
- "node"

sudo: required

cache:
  directories:
    - node_modules

services:
  - postgresql
  - docker

addons:
  postgresql: "9.6"
  hosts:
    - postgres.test.truesparrow
    - identity.test.truesparrow

env:
  global:
  #* Application *#
  - ENV=TEST
  - ADDRESS=0.0.0.0
  - PORT=10000
  - DATABASE_URL=postgresql://postgres@postgres.test.truesparrow/truesparrow
  - DATABASE_MIGRATIONS_DIR=./migrations
  - DATABASE_MIGRATIONS_TABLE=migrations_content
  - ORIGIN=null
  - CLIENTS=null
  - IDENTITY_SERVICE_HOST=null
  - LOGGLY_TOKEN=null
  - LOGGLY_SUBDOMAIN=null
  - ROLLBAR_TOKEN=null
  #* Travis build *#
  - PGSSLMODE=require
  - GEMFURY_USER=truesparrow
  # GEMFURY_API_KEY=???
  - secure: "SqfKq/ubRs400F/wbK4ImILygVhpb2l51DKKbGZaJ73OdMefGsa93hkvg+N91RECSxUScx1/HMiHB4L2tdpIH/cFu4Hcl6y0XX8cNBqyzaAUI8mMxP6YA3HBJmRviqNwyI/tqmyEArEPlFZl6jb93ixGIVAJVFTiQb3xEXENIMffb61tvMz16naDypGEe6FgM6aGhAD13YNj6JGjYzLhUm4agMzIWzLsoyROJGLLAh4jDBbW8DRI+hN9EHymm4Pcqa/fl0oTRwaKYSEmOpp28fxk9R7DNAqlivcz1b5ShjgGpuZiPvb3YaGCEXLDh2yUdN5SP/8+ZV8Z6XYC4qoOGcphWFDJ/mMpWc+owoEFBAqtIuLF0pLK4k64uENbzg2fKKEsCQsif4Yo2cIIAQq7Bd4V1RDWeJB83SwdzJhvSIcrIcJBtaXlA9BZfv6kJil3ctpQ1MxuQKgX+d5NixZZCzay4DadGjJ6Etrxj/EvXMwHKBOMqOl/6XePj1AWg8G3X9/d8tJblkmC/ReiIdp7vKPANBtK2klewt97ZSsRuKLkyMdvfSkZ3PLAAZqhJVC5UQT0oQFu1oVCI20y6dmSlCxFDdd/aiUMzQ89+79zV2IbPdm4KuxH9asv05bIpB7bB9oo8tQxy0BjZ4tA+OYnWkx25uUPAJ5dZ4W3VaS9zPs="

install:
- npm install --registry=https://npm-proxy.fury.io/${GEMFURY_API_KEY}/${GEMFURY_USER}/ --progress=false

before_script:
- psql -c 'create database truesparrow;' -U postgres
- openssl aes-256-cbc -K $encrypted_22cca5ef00ec_key -iv $encrypted_22cca5ef00ec_iv -in gcp-ci-docker-pusher-key.json.enc -out gcp-ci-docker-pusher-key.json -d

script:
- npm run test

after_success:
- npm run push-coverage-to-codecov

deploy:
- provider: script
  skip_cleanup: true
  script: $(npm bin)/togemfury --user ${GEMFURY_USER} --api_key ${GEMFURY_API_KEY}
  on:
    tags: true
- provider: script
  skip_cleanup: true
  script:
    cat gcp-ci-docker-pusher-key.json | docker login --username _json_key --password-stdin https://eu.gcr.io;
    docker build --tag eu.gcr.io/chmsqrt2-truesparrow-common/content:$TRAVIS_TAG .;
    docker push eu.gcr.io/chmsqrt2-truesparrow-common/content:$TRAVIS_TAG;
    docker build --tag eu.gcr.io/chmsqrt2-truesparrow-common/content:latest .;
    docker push eu.gcr.io/chmsqrt2-truesparrow-common/content:latest
  on:
    tags: true
